// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMOej2Ztgwmmt3rx8A77rLK2_UnCVSjtU',
    appId: '1:362887628726:web:18d60772e68c30941b2317',
    messagingSenderId: '362887628726',
    projectId: 'fyp-assist-39d60',
    authDomain: 'fyp-assist-39d60.firebaseapp.com',
    storageBucket: 'fyp-assist-39d60.firebasestorage.app',
    measurementId: 'G-FNPRTKXQHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmA4hcVqd4ojcpv5X3zuTbGCNsPbyAICk',
    appId: '1:362887628726:android:59b6811d39a1188c1b2317',
    messagingSenderId: '362887628726',
    projectId: 'fyp-assist-39d60',
    storageBucket: 'fyp-assist-39d60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIuiuTOMja08g201xtR5QJ8DnaaR5Mx8Q',
    appId: '1:362887628726:ios:8d13ffa0f4eafe851b2317',
    messagingSenderId: '362887628726',
    projectId: 'fyp-assist-39d60',
    storageBucket: 'fyp-assist-39d60.firebasestorage.app',
    iosBundleId: 'com.fyp.assist.fypAssist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIuiuTOMja08g201xtR5QJ8DnaaR5Mx8Q',
    appId: '1:362887628726:ios:8d13ffa0f4eafe851b2317',
    messagingSenderId: '362887628726',
    projectId: 'fyp-assist-39d60',
    storageBucket: 'fyp-assist-39d60.firebasestorage.app',
    iosBundleId: 'com.fyp.assist.fypAssist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMOej2Ztgwmmt3rx8A77rLK2_UnCVSjtU',
    appId: '1:362887628726:web:5602dcbcfb4d25191b2317',
    messagingSenderId: '362887628726',
    projectId: 'fyp-assist-39d60',
    authDomain: 'fyp-assist-39d60.firebaseapp.com',
    storageBucket: 'fyp-assist-39d60.firebasestorage.app',
    measurementId: 'G-S0BPJNKW0S',
  );

}